name: A simple CI pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # New step to install the linter tool
      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      # New step to run the linter on our file
      - name: Lint YAML file
        run: yamllint .github/workflows/ci-pipeline.yml
